---

- name: list of the .conf files and store it in register
  raw: find /etc/init.d/ -type f -name "redis*"
  register: raw_dir


- name: disable all repos
  lineinfile: 
    path: "{{ item }}"
    regexp: '^PIDFILE='
    line: 'PIDFILE=/var/run/redis/redis_${REDISPORT}.pid'
  with_items: "{{ raw_dir.stdout_lines }}"

- name: insert line file 
  lineinfile:
    path: "{{ item }}"
    insertbefore: '^REDISPORT='
    line: 'mkdir -p /var/run/redis ; chown redis /var/run/redis'
  with_items: "{{ raw_dir.stdout_lines }}"

- name: list of the .conf files and store it in register
  raw: find /etc/redis/ -type f -name "*.conf"
  register: red_conf_dir

- name: Get redis port
  raw: ls -ltrh /etc/init.d/ | grep redis | awk -F ' ' '{print $9}'  | awk -F'_' '{print $2}'
  register: port 


- name: Change configuration port
  shell: sed -i 's/pidfile \/home\/deploy\/redis_{{ item }}/pidfile \/var\/run\/redis/g' /etc/redis/{{ item }}.conf 
  with_items: "{{ port.stdout_lines }}"

